# Generated by Django 4.2.4 on 2023-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dtm',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
