# Generated by Django 4.2.4 on 2023-09-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_dtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='catgory',
            field=models.CharField(default='عمومی', max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='dtm',
            field=models.CharField(default='1402/06/25', max_length=10),
        ),
    ]
