# Generated by Django 4.2.4 on 2023-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_news_catgory_alter_news_dtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(default='مدیرسایت', max_length=30),
        ),
    ]
