# Generated by Django 4.2.4 on 2023-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_news_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(default='مدیرسایت', max_length=60, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='news',
            name='catgory',
            field=models.CharField(default='عمومی', max_length=30, verbose_name='گروه خبری'),
        ),
        migrations.AlterField(
            model_name='news',
            name='dtm',
            field=models.CharField(default='1402/06/25', max_length=10, verbose_name='تاریخ خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='txt',
            field=models.TextField(verbose_name='متن خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='writer',
            field=models.CharField(default='مدیرسایت', max_length=30, verbose_name='نویسنده'),
        ),
    ]
