# Generated by Django 4.2.4 on 2023-09-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_news_txt_news_pic1_news_pic2_news_pic3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='keyword',
        ),
        migrations.AddField(
            model_name='news',
            name='keyword1',
            field=models.CharField(default='هفته نامه امین بختیاری ', max_length=60, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='news',
            name='keyword2',
            field=models.CharField(default='هفته نامه امین بختیاری ', max_length=60, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='news',
            name='keyword3',
            field=models.CharField(default='هفته نامه امین بختیاری ', max_length=60, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='news',
            name='keyword4',
            field=models.CharField(default='هفته نامه امین بختیاری ', max_length=60, verbose_name='کلمات کلیدی'),
        ),
    ]
