# Generated by Django 4.2.4 on 2023-09-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_contact_alter_news_pic1_alter_news_pic2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('comentxt', models.CharField(max_length=150)),
                ('newss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.news')),
            ],
        ),
    ]
