# Generated by Django 4.2.4 on 2023-09-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic1',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
