# Generated by Django 4.2.4 on 2023-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_alter_news_pic1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic1',
            field=models.ImageField(upload_to='pictures', verbose_name='عکس دو'),
        ),
    ]
