# Generated by Django 4.2.4 on 2023-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_news_pic1'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAM', models.CharField(max_length=24, verbose_name='نام وبسایت')),
            ],
        ),
    ]
