# Generated by Django 4.2.4 on 2023-09-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_contact_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_us_table',
        ),
    ]
