# Generated by Django 4.2.4 on 2023-09-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_rename_contact_contact_us_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('email', models.CharField(max_length=50, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.CharField(max_length=500, verbose_name='پیام')),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us_table',
        ),
    ]
